version: '3.7'
services:
  redis:
    container_name: 'redis'
    image: redis:7.0.8
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  postgres:
    container_name: 'postgres'
    image: postgres:latest
    volumes:
      - postgres:/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: appuser

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  redis:

  postgres: