version: '3.7'
services:
  redis:
    container_name: 'redis'
    image: redis:7.0.8
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  postgres:
    container_name: 'postgres'
    image: postgres:latest
    volumes:
      - postgres:/data
    ports:
      - 5455:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: appuser

  adminer:
    image: adminer
    ports:
      - 8080:8080

  elasticsearch:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    volumes:
      - elastic:/data

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601


volumes:
  redis:
  postgres:
  elastic: